spring:
  application:
    name: domain
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: 111
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

