spring:
  application:
    name: domain
  kafka:
    bootstrap-servers: http://localhost:9092
    consumer:
      group-id: task-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    username: postgres
    password: 111
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8088

