spring:
  application:
    name: notification-service
  kafka:
    task-service-topic: task-service
    consumer:
      group-id: notification-service
      bootstrap-servers: localhost:9092
  mail:
    host: domain.mail.yandex.net
    port: 587
    username: admin@digit-os.ru
    password: 2025Admin
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8085